First heading
Sergiomerizalde/exercise-collaborative-html-website pull request #3
Opened 2022-07-28 02:57 UTC by adncb

2022-07-29 21:31 UTC, Wishmastering requested changes
Falta el bg-white en el primer div "para poner background blanco"

Falta "dividir en cols y que se centre un poco el text e imagen" , para eso hice un "col-1" a la derecha y a la izq.

Dejandome un "col-7" para el texto y un "col-3" para la imagen.

La imagen debemos tomarla de "assets" directamente con el "Copy path" y seria exactamente como en la del sitio web que debemos imitar

////
El codigo de esta seccion que yo hice, se ve asi ->
[first_heading.txt](https://github.com/Sergiomerizalde/exercise-collaborative-html-website/files/9223328/first_heading.txt)

2022-07-29 23:35 UTC, Sergiomerizalde approved these changes

2022-08-02 02:10 UTC, Franz8818 approved these changes

2022-08-02 02:11 UTC, merged

2022-08-02 02:11 UTC, Franz8818 approved these changes